/** 平日食器 menu stories — zh / en / ja / ko */
window.PINGRI_DISHES = [
  {
    id: "taxiang",
    cat: "signature",
    price: 170,
    image: "../images/taxiang-yidon.png",
    zh: { name: "塔香一丼", sub: "三杯雞", what: "台式三杯雞蓋飯", story: "九層塔香氣先撲上桌，醬油、麻油與米酒收成亮亮的醬汁，蓋在熱飯上。不是居酒屋的炸物丼，是台灣家常三杯味做成定食。" },
    en: { name: "Tower of Basil Bowl", sub: "Three-Cup Chicken Donburi", what: "Taiwanese three-cup chicken over rice", story: "Thai basil hits first, then a glossy sauce of soy, sesame oil, and rice wine over hot rice. Home-style Taiwanese three-cup flavor, plated as a weekday donburi." },
    ja: { name: "タワーバジル丼", sub: "台湾風三杯鶏丼", what: "台湾の三杯鶏ごはん", story: "九層塔（タイバジル）の香りが立ち、醤油・ごま油・米酒の照りあるソースが熱々のごはんに。居酒屋の揚げ物丼ではなく、台湾家庭の「三杯」を定食にした一品です。" },
    ko: { name: "바질 향 덮밥", sub: "타이완 삼배계(三杯雞)", what: "타이완식 삼배계 덮밥", story: "타이 바질 향이 먼저 퍼지고, 간장·참기름·미림 계열 소스가 따뜻한 밥 위에 윤기 나게 올라갑니다. 이자카야 튀김 덮밥이 아니라, 타이완 집밥 삼배계를 정식으로 담은 메뉴입니다." }
  },
  {
    id: "weixi",
    cat: "signature",
    price: 165,
    image: "../images/weicen-xiangko.png",
    zh: { name: "味噌巷口", sub: "滷肉飯", what: "台式滷肉飯（微味噌香）", story: "巷口滷肉的鹹香，加一點味噌的溫潤，配溏心蛋與小菜。外國朋友可以想成：台灣最日常的肉燥飯，再多一層日式味噌餘韻。" },
    en: { name: "Miso Alley Bowl", sub: "Braised Pork Rice", what: "Taiwanese lu rou fan with a hint of miso", story: "Salty-sweet braised minced pork like a night-market classic, softened with a touch of miso, plus soft egg and pickles. Think Taiwan’s everyday pork rice with a gentle Japanese aftertaste." },
    ja: { name: "味噌の路地丼", sub: "ルーロー飯", what: "台湾ルーロー飯（味噌の香り）", story: "路地裏のルーロー（煮込み豚そぼろ）の旨みに、味噌のまろやかさを重ね、半熟卵と小菜添え。台湾の日常ごはんに、和の余韻を少し足した一品です。" },
    ko: { name: "미소 골목 덮밥", sub: "타이완 루로우판", what: "타이완식 돼지고기 덮밥(미소 향)", story: "골목 분식집 느낌의 짭조름달콤한 돼지고기 볶음에 미소의 부드러운 맛을 더하고, 반숙란과 반찬을 곁들입니다. 타이완의 일상 덮밥에 일본식 여운이 살짝 남는 메뉴입니다." }
  },
  {
    id: "congian",
    cat: "don",
    price: 165,
    image: "../images/cong-yan-wuhou.png",
    zh: { name: "蔥鹽午後", sub: "雞腿丼", what: "蔥鹽烤雞腿蓋飯", story: "烤過的雞腿切厚片，灑滿青蔥與鹽香，配半熟蛋。像午後陽光一樣清爽，適合想吃肉又不想太重口的日子。" },
    en: { name: "Scallion-Salt Afternoon", sub: "Chicken Thigh Donburi", what: "Roasted chicken thigh rice bowl with scallion salt", story: "Thick slices of roasted chicken thigh under a pile of green onion and salt seasoning, with a soft egg. Bright and clean—good when you want meat without a heavy sauce." },
    ja: { name: "ネギ塩の午後", sub: "鶏もも丼", what: "ネギ塩ローストチキン丼", story: "焼き上げた鶏ももを厚切りにし、青ねぎと塩の香りをたっぷり。半熟卵添えで、午後の光のようにさっぱり。がっつりしつつ重すぎない一皿です。" },
    ko: { name: "파소금 오후", sub: "닭다리살 덮밥", what: "파소금 구운 닭다리 덮밥", story: "구운 닭다리살을 두툼하게 썰어 파와 소금 양념을 올리고 반숙란을 곁들입니다. 오후 햇살처럼 산뜻해서, 고기는 먹고 싶지만 무거운 소스는 싫은 날에 잘 맞습니다." }
  },
  {
    id: "maxi",
    cat: "don",
    price: 155,
    image: "../images/maxi-hongyou.png",
    zh: { name: "麻香紅油", sub: "豆腐丼", what: "家常麻香紅油豆腐丼", story: "麻香不嗆喉，收進丼裡就走。" },
    en: { name: "Mala Chili Oil", sub: "Tofu Donburi", what: "Mapo-style tofu donburi with gentle chili fragrance", story: "Comforting heat, ready to go." },
    ja: { name: "麻香紅油", sub: "豆腐丼", what: "麻辣香る豆腐丼", story: "刺激すぎない家常の辛さで、サッと食べて出勤にも。" },
    ko: { name: "마향홍유", sub: "두부 덮밥", what: "마파 향의 두부 덮밥", story: "자극적이지 않은 집밥 매콤함, 빠르게 한 끼." }
  },
  {
    id: "suanhuo",
    cat: "don",
    price: 190,
    image: "../images/suanhuo-mankao.png",
    zh: { name: "蒜火慢烤", sub: "排骨定食", what: "蒜香慢烤排骨定食", story: "蒜香排骨，定食一次滿足。" },
    en: { name: "Garlic Slow Roast", sub: "Pork Rib Set", what: "Garlic slow-roast pork rib set meal", story: "Savory garlic ribs in one complete meal." },
    ja: { name: "蒜火慢烤", sub: "排骨定食", what: "ニンニク香るスペアリブ定食", story: "ガッツリ満足の一皿。" },
    ko: { name: "산화만고", sub: "갈비 정식", what: "마늘 향 폭립 정식", story: "한번 시키면 든든하게 끝나는 한 상." }
  },
  {
    id: "zhaoshao",
    cat: "don",
    price: 200,
    image: "../images/zhaoshao-houqie.png",
    zh: { name: "照燒厚切", sub: "豬排飯", what: "厚切照燒豬排飯", story: "厚切豬排，照燒亮汁。" },
    en: { name: "Glazed Thick Cut", sub: "Pork Cutlet Rice", what: "Thick-cut pork with glossy teriyaki glaze over rice", story: "Juicy cut, shiny glaze." },
    ja: { name: "照焼厚切", sub: "豚排飯", what: "厚切りトンテキ風の照り焼き豚ごはん", story: "ツヤのあるタレがご飯に合う。" },
    ko: { name: "데리야키 후컷", sub: "돈까스 덮밥", what: "두툼한 데리야키 돼지덮밥", story: "윤기 나는 소스가 포인트." }
  },
  {
    id: "congyou",
    cat: "noodle",
    price: 160,
    image: "../images/congyou-xilang.png",
    zh: { name: "蔥油細浪", sub: "雞絲麵", what: "蔥油雞絲麵", story: "蔥油雞絲，平日快速一碗。" },
    en: { name: "Scallion Oil Waves", sub: "Chicken Noodles", what: "Scallion-oil noodles with shredded chicken", story: "A fast weekday bowl." },
    ja: { name: "葱油細浪", sub: "鶏絲麺", what: "ネギ油香る鶏しぐれ風麺", story: "平日の早い一杯に。" },
    ko: { name: "파기름 세랑", sub: "닭고기 면", what: "파기름 닭고기 면", story: "평일에도 부담 없이 빠른 한 그릇." }
  },
  {
    id: "hongshao",
    cat: "noodle",
    price: 220,
    image: "../images/hongshao-tangyun.png",
    zh: { name: "紅燒湯韻", sub: "牛肉拉麵", what: "紅燒牛肉拉麵", story: "慢燉紅燒湯頭，配有嚼勁的拉麵與牛肉。台式牛肉麵的魂，用拉麵的口感重新組裝——湯韻是關鍵。" },
    en: { name: "Braised Broth Melody", sub: "Beef Ramen", what: "Taiwanese-style braised beef noodle soup (ramen)", story: "A slow braised soy-beef broth with chewy ramen and beef. The soul of Taiwanese beef noodle soup, rebuilt with ramen texture—the broth is the star." },
    ja: { name: "紅焼の湯韻", sub: "牛肉ラーメン", what: "台湾風紅焼牛肉ラーメン", story: "じっくり煮込んだ紅焼スープに、コシのある麺と牛肉。台湾牛肉麺の魂を、ラーメンの食感で再構成。スープの余韻が主役です。" },
    ko: { name: "홍샤오 국물 운율", sub: "소고기 라멘", what: "타이완식 홍샤오 소고기 라멘", story: "천천히 끓인 홍샤오(간장 조림) 국물에 쫄깃한 라멘과 소고기. 타이완 우육면의 영혼을 라멘 식감으로 다시 담았습니다—국물 여운이 핵심입니다." }
  },
  {
    id: "yanchi",
    cat: "noodle",
    price: 220,
    image: "../images/yanchi-hai-o.png",
    zh: { name: "蔭豉海蚵", sub: "炒烏龍", what: "台式蔭豉鮮蚵炒烏龍", story: "台式蔭豉鮮蚵，炒進烏龍。" },
    en: { name: "Black Bean Oyster", sub: "Stir-fried Udon", what: "Stir-fried udon with oysters and Taiwanese fermented black bean", story: "Ocean umami wokked into the noodles." },
    ja: { name: "蔭豉海蚵", sub: "焼きうどん", what: "台湾風豆豉と牡蠣の焼きうどん", story: "海の旨みをしっかり炒め込み。" },
    ko: { name: "음시 굴", sub: "볶음 우동", what: "대만식 발효콩과 굴 볶음 우동", story: "바다 감칠맛을 면에 볶아 넣음." }
  },
  {
    id: "zhengyun",
    cat: "soup",
    price: 55,
    image: "../images/zhengyun-jizhong.png",
    zh: { name: "蒸雲雞盅", sub: "蛋豆腐雞湯", what: "蛋香蒸雞盅湯", story: "蛋香蒸湯，溫熱補一口。" },
    en: { name: "Steamed Cloud Chicken", sub: "Egg Tofu Chicken Soup", what: "Steamed chicken soup with egg tofu", story: "Warm, gentle, comforting." },
    ja: { name: "蒸雲鶏盅", sub: "卵豆腐鶏湯", what: "卵豆腐入りの蒸し鶏スープ", story: "やさしく温まる一杯。" },
    ko: { name: "증운 닭중", sub: "계란두부 닭국", what: "계란두부 찜 닭국", story: "따뜻하고 부드러운 한 모금." }
  },
  {
    id: "shanshu",
    cat: "soup",
    price: 60,
    image: "../images/shanshu-zhusheng.png",
    zh: { name: "山蔬竹笙盅", sub: "香菇竹笙湯", what: "清爽香菇竹笙蒸湯", story: "清爽菇筍，素食友善。" },
    en: { name: "Mountain Veg Bamboo Pith", sub: "Mushroom Bamboo Soup", what: "Light mushroom and bamboo pith steamed soup", story: "Fresh, vegetarian-friendly." },
    ja: { name: "山蔬竹笙盅", sub: "香菇竹笙湯", what: "きのこ竹笙の蒸しスープ", story: "さっぱり、ベジ対応。" },
    ko: { name: "산소 죽생중", sub: "버섯 죽순국", what: "버섯·죽순 찜국", story: "담백하고 채식 친화적." }
  },
  {
    id: "suansiang",
    cat: "soup",
    price: 85,
    image: "../images/suansiang-geli.png",
    zh: { name: "蒜香蛤蜊盅", sub: "蛤蜊蒸湯", what: "蒜香蛤蜊蒸湯", story: "蒜香蛤蜊，蒸到開口。" },
    en: { name: "Garlic Clam Cup", sub: "Steamed Clam Soup", what: "Garlic steamed clam soup", story: "Clams opened over aromatic steam." },
    ja: { name: "蒜香蛤蜊盅", sub: "あさり蒸しスープ", what: "ニンニク香るあさりの蒸しスープ", story: "口を開けた瞬間が旬のしるし。" },
    ko: { name: "마늘 바지락중", sub: "바지락 찜국", what: "마늘 바지락 찜국", story: "껍질이 벌어질 때까지 쪄낸 향." }
  },
  {
    id: "tangxin",
    cat: "side",
    price: 30,
    image: "../images/tangxin-dan.png",
    zh: { name: "半熟溏心", sub: "蛋", what: "半熟溏心蛋", story: "溏心剛好，配飯配麵。" },
    en: { name: "Jammy Soft Egg", sub: "Egg", what: "Soft jammy egg", story: "Perfect with rice or noodles." },
    ja: { name: "半熟溏心", sub: "卵", what: "半熟味玉風", story: "ご飯にも麺にも合うとろ〜り黄身。" },
    ko: { name: "반숙 탕심", sub: "계란", what: "반숙 계란", story: "밥이든 면이든 잘 어울리는 노른자." }
  },
  {
    id: "ziwu",
    cat: "side",
    price: 30,
    image: "../images/ri-chang-ziwu.png",
    zh: { name: "日常漬物", sub: "小菜", what: "店內日常漬物", story: "酸香解膩，定食配角。" },
    en: { name: "Daily Pickles", sub: "Side", what: "House pickles", story: "Bright acidity to cut richness beside your set." },
    ja: { name: "日常漬物", sub: "小菜", what: "店仕込みの漬け物", story: "定食の油を切る名脇役。" },
    ko: { name: "일상 절임", sub: "반찬", what: "하우스 피클", story: "정식의 기름기를 덜어주는 산뜻함." }
  },
  {
    id: "huanggua",
    cat: "side",
    price: 35,
    image: "../images/qingshuang-huanggua.png",
    zh: { name: "青爽黃瓜", sub: "涼拌", what: "涼拌青瓜", story: "凉拌黃瓜，清爽收尾。" },
    en: { name: "Crisp Cucumber", sub: "Cold Salad", what: "Chilled cucumber salad", story: "Crisp, clean finish." },
    ja: { name: "青爽黄瓜", sub: "凉拌", what: "きゅうりサラダ", story: "シャキッと締める一皿。" },
    ko: { name: "청상 오이", sub: "냉채", what: "오이 냉채", story: "아삭하고 깔끔한 마무리." }
  },
  {
    id: "bento-lurou",
    cat: "bento",
    price: 160,
    image: "../images/xiangko-lurou-bento.png",
    zh: { name: "巷口滷肉", sub: "便當", what: "外帶滷肉便當", story: "給趕時間的平日：滷肉飯精神裝進便當盒，方便帶走。" },
    en: { name: "Alley Braised Pork", sub: "Bento", what: "Takeout braised-pork bento", story: "For busy weekdays: the spirit of lu rou fan packed to go." },
    ja: { name: "路地のルーロー", sub: "弁当", what: "持ち帰りルーロー弁当", story: "忙しい平日に。ルーロー飯の旨みを弁当に詰めて。" },
    ko: { name: "골목 루로우", sub: "도시락", what: "포장 루로우 도시락", story: "바쁜 평일을 위해. 루로우판의 맛을 도시락에 담아 가져갑니다." }
  },
  {
    id: "bento-shaorou",
    cat: "bento",
    price: 165,
    image: "../images/tanhuo-shaorou-bento.png",
    zh: { name: "炭火燒肉", sub: "便當（升級）", what: "醬燒肉片外帶便當", story: "醬燒肉片，外帶升級。" },
    en: { name: "Charcoal Glazed Pork", sub: "Bento (Upgrade)", what: "Char-sauced pork bento upgrade", story: "Glazed slices for takeout." },
    ja: { name: "炭火焼肉", sub: "弁当（アップグレード）", what: "炭火風のタレ焼き肉弁当", story: "持ち帰り向けの満足感。" },
    ko: { name: "숯불 구이", sub: "도시락(업그레이드)", what: "숯불 풍 양념 돼지고기 도시락", story: "포장용으로 든든한 한 끼." }
  }
];

window.PINGRI_I18N = {
  zh: {
    pageTitle: "菜品故事",
    brand: "平日食器",
    lead: "左邊是文藝菜名，右邊是實際吃什麼。例：塔香一丼｜三杯雞。外國朋友可切換語言，看「這是什麼」。",
    leadShort: "菜名｜實際料理",
    what: "這是什麼",
    story: "故事／說明",
    price: "價格",
    pendingPhoto: "菜圖準備中",
    cats: { signature: "招牌", don: "定食／丼", noodle: "麵／炒", soup: "蒸湯", side: "小菜", bento: "外帶便當" },
    back: "回官網",
    langLabel: "語言",
    aboutDish: "了解這道"
  },
  en: {
    pageTitle: "Dish Stories",
    brand: "Pingri Shiqiu",
    lead: "Poetic name on the left, what it really is on the right. e.g. Tower Basil Bowl | Three-Cup Chicken. Switch language to see what you’re ordering.",
    leadShort: "Name | What it is",
    what: "What it is",
    story: "Story",
    price: "Price",
    pendingPhoto: "Photo coming soon",
    cats: { signature: "Signatures", don: "Teishoku / Don", noodle: "Noodles / Stir-fry", soup: "Steamed soups", side: "Sides", bento: "Takeout bento" },
    back: "Back to site",
    langLabel: "Language",
    aboutDish: "About this dish"
  },
  ja: {
    pageTitle: "お品書きストーリー",
    brand: "平日食器",
    lead: "左は創作名、右は実際の料理。例：塔香一丼｜三杯鶏。言語を切り替えて「何の料理か」を確認できます。",
    leadShort: "名前｜実際の料理",
    what: "これは何か",
    story: "ストーリー",
    price: "価格",
    pendingPhoto: "写真準備中",
    cats: { signature: "看板", don: "定食／丼", noodle: "麺／炒め", soup: "蒸しスープ", side: "小菜", bento: "テイクアウト弁当" },
    back: "トップへ",
    langLabel: "言語",
    aboutDish: "この一品について"
  },
  ko: {
    pageTitle: "메뉴 이야기",
    brand: "평일식기",
    lead: "왼쪽은 감각적인 이름, 오른쪽은 실제 메뉴. 예: 탑향일동｜산베이 치킨. 언어를 바꿔 「이게 무슨 음식인지」 확인하세요.",
    leadShort: "이름｜실제 메뉴",
    what: "어떤 음식인가요",
    story: "이야기",
    price: "가격",
    pendingPhoto: "사진 준비 중",
    cats: { signature: "시그니처", don: "정식／덮밥", noodle: "면／볶음", soup: "찜국", side: "반찬", bento: "포장 도시락" },
    back: "홈으로",
    langLabel: "언어",
    aboutDish: "이 요리 소개"
  }
};

/** Homepage chrome (nav / sections / CTAs) — zh / en / ja / ko */
window.PINGRI_HOME = {
  zh: {
    title: "平日食器｜台式融合定食",
    description: "平日快速的台式×日式新定食。家常味重新組裝。林口長庚／福樺水悅商圈。",
    navAria: "主要",
    nav: { brand: "品牌", space: "店景", sig: "招牌", menu: "菜單", dishes: "菜品故事", takeout: "外帶", location: "地點" },
    ctaMenu: "看菜單",
    kicker: "平日食器",
    heroTitle: "平日快速的台式×日式新定食",
    heroLead: "家常味重新組裝，不是熱炒、不是純日料。給林口長庚／福樺水悅商圈，好好吃一頓平日飯。",
    ctaTakeout: "外帶說明",
    ctaLoc: "地點",
    heroMeta: "選址籌備中｜地址即將公布",
    heroCapL: "店景",
    heroCapR: "裝潢後外觀",
    brandLabel: "品牌",
    brandTitle: "關於平日食器",
    brandLead: "我們把台式家常味做成定食與丼：出餐俐落，適合平日好好吃飯。菜名可以文藝一點，點餐仍然一眼看懂。",
    note1Title: "台式 × 日式",
    note1Body: "溫暖清楚、好點好走。宣紙感與鼠尾草配色，文藝但不難懂。",
    note2Title: "菜名｜實際料理",
    note2Body: "左邊是文藝菜名，右邊是實際吃什麼。例：塔香一丼｜三杯雞——點餐一眼看懂。",
    spaceLabel: "店景",
    spaceTitle: "空間與氛圍",
    spaceLead: "紙感米白、暖沙與鼠尾草，像走進一間安靜的平日食堂。",
    spaceExt: "店面外觀",
    spaceExtSub: "林口長庚／福樺水悅商圈（裝潢後｜地址籌備公布）",
    spaceInt: "店內",
    spaceIntSub: "留白乾淨，適合平日坐下吃飯",
    sigLabel: "招牌",
    sigTitle: "先記住兩道",
    sigLead: "招牌兩道，再往下逛完整菜單。",
    menuLabel: "菜單",
    menuTitle: "完整菜單",
    menuLeadBefore: "菜名｜實際料理＋價格。想看每道菜是什麼、多語說明（中／英／日／韓），請看 ",
    menuLeadLink: "菜品故事",
    menuLeadAfter: "。",
    mhExtra: " · 菜單 v1.1",
    takeLabel: "外帶",
    takeTitle: "平日外帶",
    takeLead: "午晚尖峰為主。定食可內用，便當主打外帶；也適合陪病／輪班補給。",
    takePt1Title: "平日快速",
    takePt1Body: "結構清楚、出餐動線短，適合午休與下班一餐。",
    takePt2Title: "外帶／麵食重點",
    takePt3Title: "點餐方式",
    takePt3Body: "官網先看菜單；線上點餐／外送上線後補上。",
    locLabel: "地點",
    locTitle: "來店與開幕通知",
    locAddr: "林口長庚／福樺水悅商圈",
    locHint: "籌備／試營運資訊即將公布｜地址即將公布",
    locPill: "即將開幕",
    locFormLead: "留下信箱，開幕與試營運時通知你。（占位，尚未接後端）",
    emailLabel: "信箱",
    notifyBtn: "告訴我開幕了",
    formNote: "占位表單 · 不會真的送出",
    formDone: "已記錄（示範）。正式上線後會接真實通知。",
    footerLine: "台式融合定食 · 台式×日式定食／丼"
  },
  en: {
    title: "Pingri Shiqiu｜Taiwanese–Japanese Teishoku",
    description: "Weekday-fast Taiwanese × Japanese teishoku. Home flavors, rebuilt. Linkou Chang Gung / Fuhua Shuiyue.",
    navAria: "Main",
    nav: { brand: "Brand", space: "Space", sig: "Signatures", menu: "Menu", dishes: "Dish stories", takeout: "Takeout", location: "Location" },
    ctaMenu: "See menu",
    kicker: "Pingri Shiqiu",
    heroTitle: "Weekday-fast Taiwanese × Japanese teishoku",
    heroLead: "Home flavors, rebuilt—not stir-fry, not pure Japanese. A proper weekday meal near Linkou Chang Gung / Fuhua Shuiyue.",
    ctaTakeout: "Takeout",
    ctaLoc: "Location",
    heroMeta: "Location in progress｜Address coming soon",
    heroCapL: "Storefront",
    heroCapR: "After fit-out",
    brandLabel: "Brand",
    brandTitle: "About Pingri Shiqiu",
    brandLead: "Taiwanese home cooking as teishoku and donburi: quick service for a good weekday meal. Names can be poetic; ordering stays clear.",
    note1Title: "Taiwanese × Japanese",
    note1Body: "Warm and clear—easy to order, easy to go. Paper-rice tones and sage green: literary, never confusing.",
    note2Title: "Name | What it is",
    note2Body: "Poetic name on the left, what it really is on the right. e.g. Tower Basil Bowl | Three-Cup Chicken—clear at a glance.",
    spaceLabel: "Space",
    spaceTitle: "Space & mood",
    spaceLead: "Paper white, warm sand, and sage—like a quiet weekday cafeteria.",
    spaceExt: "Exterior",
    spaceExtSub: "Linkou Chang Gung / Fuhua Shuiyue (after fit-out｜address TBA)",
    spaceInt: "Interior",
    spaceIntSub: "Clean space to sit and eat on a weekday",
    sigLabel: "Signatures",
    sigTitle: "Remember these two",
    sigLead: "Two signatures, then the full menu below.",
    menuLabel: "Menu",
    menuTitle: "Full menu",
    menuLeadBefore: "Name | What it is + price. For what’s in each dish (ZH/EN/JA/KO), see ",
    menuLeadLink: "Dish stories",
    menuLeadAfter: ".",
    mhExtra: " · Menu v1.1",
    takeLabel: "Takeout",
    takeTitle: "Weekday takeout",
    takeLead: "Lunch and dinner peaks. Teishoku for dine-in; bento for takeout—also good for hospital shifts.",
    takePt1Title: "Weekday-fast",
    takePt1Body: "Clear structure, short kitchen path—good for lunch break or after work.",
    takePt2Title: "Takeout / noodles",
    takePt3Title: "How to order",
    takePt3Body: "Browse the menu here; online order / delivery coming later.",
    locLabel: "Location",
    locTitle: "Visit & opening alerts",
    locAddr: "Linkou Chang Gung / Fuhua Shuiyue",
    locHint: "Prep / soft-open info soon｜Address TBA",
    locPill: "Opening soon",
    locFormLead: "Leave your email for opening & soft-open news. (Placeholder—no backend yet.)",
    emailLabel: "Email",
    notifyBtn: "Tell me when you open",
    formNote: "Placeholder form · nothing is sent",
    formDone: "Noted (demo). Real alerts when we go live.",
    footerLine: "Taiwanese fusion teishoku · Taiwanese × Japanese sets / don"
  },
  ja: {
    title: "平日食器｜台湾×日本の定食",
    description: "平日にサッと食べる台湾×日本の新定食。家庭の味を再構築。林口長庚／福樺水悦。",
    navAria: "メイン",
    nav: { brand: "ブランド", space: "店内", sig: "看板", menu: "メニュー", dishes: "お品書き", takeout: "テイクアウト", location: "アクセス" },
    ctaMenu: "メニューを見る",
    kicker: "平日食器",
    heroTitle: "平日にサッと、台湾×日本の新定食",
    heroLead: "家庭の味を再構成。熱炒でも純粋な和食でもない。林口長庚／福樺水悦で、平日のごはんをきちんと。",
    ctaTakeout: "テイクアウト",
    ctaLoc: "アクセス",
    heroMeta: "出店準備中｜住所は近日公開",
    heroCapL: "外観",
    heroCapR: "内装後",
    brandLabel: "ブランド",
    brandTitle: "平日食器について",
    brandLead: "台湾の家庭の味を定食と丼に。出膳が早く、平日にきちんと食べられる。名前は少し詩的でも、注文は一目でわかる。",
    note1Title: "台湾 × 日本",
    note1Body: "温かくわかりやすく、頼みやすく行きやすい。宣紙のような色とセージグリーン。文学的でも難しくない。",
    note2Title: "名前｜実際の料理",
    note2Body: "左は創作名、右は実際の料理。例：塔香一丼｜三杯鶏——注文が一目でわかる。",
    spaceLabel: "店内",
    spaceTitle: "空間と雰囲気",
    spaceLead: "紙のようなオフホワイト、暖かな砂色、セージ。静かな平日食堂のよう。",
    spaceExt: "外観",
    spaceExtSub: "林口長庚／福樺水悦（内装後｜住所準備中）",
    spaceInt: "店内",
    spaceIntSub: "余白のある空間で、平日に座って食べる",
    sigLabel: "看板",
    sigTitle: "まずこの二品",
    sigLead: "看板二品のあと、フルメニューへ。",
    menuLabel: "メニュー",
    menuTitle: "フルメニュー",
    menuLeadBefore: "名前｜実際の料理＋価格。各料理の多言語説明は ",
    menuLeadLink: "お品書きストーリー",
    menuLeadAfter: " へ。",
    mhExtra: " · メニュー v1.1",
    takeLabel: "テイクアウト",
    takeTitle: "平日テイクアウト",
    takeLead: "昼・夜のピーク向け。定食は店内、弁当は持ち帰り。付き添い・シフトの補給にも。",
    takePt1Title: "平日スピード",
    takePt1Body: "構成がはっきり、動線が短い。昼休みや退勤後に。",
    takePt2Title: "テイクアウト／麺",
    takePt3Title: "注文方法",
    takePt3Body: "まずはこのメニューを。オンライン注文／配達は後日。",
    locLabel: "アクセス",
    locTitle: "来店とオープン通知",
    locAddr: "林口長庚／福樺水悦エリア",
    locHint: "準備／ソフトオープン情報は近日｜住所は近日公開",
    locPill: "まもなくオープン",
    locFormLead: "メールを残すとオープン・ソフトオープンをお知らせします。（仮・バックエンド未接続）",
    emailLabel: "メール",
    notifyBtn: "オープンを知らせて",
    formNote: "仮フォーム · 送信されません",
    formDone: "記録しました（デモ）。本番では実通知に接続します。",
    footerLine: "台湾フュージョン定食 · 台湾×日本の定食／丼"
  },
  ko: {
    title: "평일식기｜타이완×일식 정식",
    description: "평일에 빠르게 먹는 타이완×일식 신정식. 집밥을 다시 조립. 린커우 창겅／푸화수웨.",
    navAria: "주요",
    nav: { brand: "브랜드", space: "매장", sig: "시그니처", menu: "메뉴", dishes: "메뉴 이야기", takeout: "포장", location: "위치" },
    ctaMenu: "메뉴 보기",
    kicker: "평일식기",
    heroTitle: "평일에 빠르게, 타이완×일식 신정식",
    heroLead: "집밥을 다시 조립했습니다. 열차오도, 순수 일식도 아닌. 린커우 창겅／푸화수웨에서 평일 한 끼를 제대로.",
    ctaTakeout: "포장 안내",
    ctaLoc: "위치",
    heroMeta: "입지 준비 중｜주소 곧 공개",
    heroCapL: "외관",
    heroCapR: "인테리어 후",
    brandLabel: "브랜드",
    brandTitle: "평일식기 소개",
    brandLead: "타이완 집밥을 정식과 덮밥으로. 출식이 빠르고 평일에 제대로 한 끼. 이름은 감각적으로, 주문은 한눈에.",
    note1Title: "타이완 × 일식",
    note1Body: "따뜻하고 분명하게, 고르기 쉽고 가기 쉽게. 선지 느낌과 세이지 그린—문학적이나 어렵지 않아요.",
    note2Title: "이름｜실제 메뉴",
    note2Body: "왼쪽은 감각적인 이름, 오른쪽은 실제 메뉴. 예: 탑향일동｜산베이 치킨—주문 한눈에.",
    spaceLabel: "매장",
    spaceTitle: "공간과 분위기",
    spaceLead: "종이 느낌의 미색, 따뜻한 모래색, 세이지. 조용한 평일 식당처럼.",
    spaceExt: "외관",
    spaceExtSub: "린커우 창겅／푸화수웨 (인테리어 후｜주소 준비 중)",
    spaceInt: "내부",
    spaceIntSub: "여백이 있는 공간에서 평일 식사",
    sigLabel: "시그니처",
    sigTitle: "먼저 이 두 가지",
    sigLead: "시그니처 두 가지 다음, 전체 메뉴로.",
    menuLabel: "메뉴",
    menuTitle: "전체 메뉴",
    menuLeadBefore: "이름｜실제 메뉴＋가격. 각 요리의 다국어 설명은 ",
    menuLeadLink: "메뉴 이야기",
    menuLeadAfter: "에서.",
    mhExtra: " · 메뉴 v1.1",
    takeLabel: "포장",
    takeTitle: "평일 포장",
    takeLead: "점심·저녁 피크 중심. 정식은 매장, 도시락은 포장. 병간호·교대 근무 보급에도.",
    takePt1Title: "평일 빠르게",
    takePt1Body: "구성이 분명하고 동선이 짧아 점심·퇴근 후 한 끼에 좋습니다.",
    takePt2Title: "포장／면 메뉴",
    takePt3Title: "주문 방법",
    takePt3Body: "먼저 이 메뉴를 보세요. 온라인 주문／배달은 추후.",
    locLabel: "위치",
    locTitle: "방문과 오픈 알림",
    locAddr: "린커우 창겅／푸화수웨 상권",
    locHint: "준비／소프트 오픈 정보 곧｜주소 곧 공개",
    locPill: "곧 오픈",
    locFormLead: "이메일을 남기면 오픈·소프트 오픈을 알려드립니다. (자리 표시·백엔드 미연결)",
    emailLabel: "이메일",
    notifyBtn: "오픈하면 알려주세요",
    formNote: "자리 표시 폼 · 실제 전송 없음",
    formDone: "기록됨(데모). 정식 런칭 후 실제 알림 연결.",
    footerLine: "타이완 퓨전 정식 · 타이완×일식 정식／덮밥"
  }
};
